apiVersion: v1
kind: ConfigMap
metadata:
  name: xg-tsla-svc-dev-config
data:
  application.yml: |-
    spring:
      application:
        name: xg-tsla-svc
        config:
          import: classpath:ollama-prompts.yaml  
      datasource:
        url: jdbc:postgresql://timescaledb:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        open-in-view: false
    springdoc:
      api-docs:
        enabled: true
        path: '/v3/api-docs'
      swagger-ui:
        url: '/xg-tsla-svc/v3/api-docs'
        path: '/swagger-ui'
        config-url: '/xg-tsla-svc/v3/api-docs/swagger-config'
    openapi:
      servers:
        prod: https://api-dev.xuyang.dev/xg-tsla-svc
    app:
      env: dev
    massive:
      api:
        base-url: https://api.massive.com
        cron: "0 0 9 * * *"
        price-cron: "0 * * * * *"
    yahoo:
      finance:
        base-url: https://query1.finance.yahoo.com
        price-5min-cron: "0 0 * * * MON-FRI"
    ollama:
      base-url: http://192.168.1.82:11434
      model: gemma4:26b
    logging:
      level:
        xuyang.dev.xgtslasvc: DEBUG
        org.hibernate.SQL: DEBUG
        org.springframework.web: INFO    
    server:
      servlet:
        context-path: /xg-tsla-svc
      forward-headers-strategy: framework
