apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: xgao-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      automountServiceAccountToken: false
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: xg-tsla-svc-dev-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xg-tsla-svc-dev-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: xg-tsla-svc-dev-secret
                  key: POSTGRES_DB
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            requests:
              memory: 256Mi
              cpu: 0.25
              ephemeral-storage: "1Gi"
            limits:
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - tsla_user
                - -d
                - tsla_db
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - tsla_user
                - -d
                - tsla_db
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: timescaledb-data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
