apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-pv-dev
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/data/xuyang.dev/dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  namespace: xgao-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: timescaledb-pv-dev
  resources:
    requests:
      storage: 50Gi
